spring:
  datasource:
    url: jdbc:mysql://sql.freedb.tech:3306/freedb_taskmanager
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: freedb_taskmanageradmin
    password: 8D?Xf8#6y9GVekK
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
spring-doc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha

