spring:
  datasource:
    url: jdbc:mysql://root:o2PThfSoQgYMvBTDAjYM@containers-us-west-194.railway.app:6058/railway
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: o2PThfSoQgYMvBTDAjYM
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
spring-doc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha

